-- Cached AI-generated customer profiles. One row per customer.
-- Regenerated by the generate-customer-profile Edge Function whenever a new
-- "Hvad blev lavet?" note is saved.

CREATE TABLE IF NOT EXISTS public.customer_ai_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  profile_text text NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  note_count int NOT NULL DEFAULT 0,
  CONSTRAINT customer_ai_profiles_customer_id_key UNIQUE (customer_id)
);

CREATE INDEX IF NOT EXISTS idx_customer_ai_profiles_customer_id
ON public.customer_ai_profiles(customer_id);

ALTER TABLE public.customer_ai_profiles ENABLE ROW LEVEL SECURITY;

-- Authenticated admin/barber users can read profiles (RLS already restricts
-- access to authenticated requests via the anon/auth key boundary).
CREATE POLICY "Authenticated can read customer_ai_profiles"
  ON public.customer_ai_profiles
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Service role (used by the Edge Function) can write.
CREATE POLICY "Service role can write customer_ai_profiles"
  ON public.customer_ai_profiles
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
