-- Cached AI-generated business overviews. One row per period_months value.
-- Regenerated by the generate-business-overview Edge Function (or weekly when
-- the cached row is older than 7 days, checked client-side).

CREATE TABLE IF NOT EXISTS public.business_overviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  period_months int NOT NULL,
  summary_text text NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  stats_json jsonb,
  CONSTRAINT business_overviews_period_months_key UNIQUE (period_months)
);

CREATE INDEX IF NOT EXISTS idx_business_overviews_period_months
ON public.business_overviews(period_months);

ALTER TABLE public.business_overviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can read business_overviews"
  ON public.business_overviews
  FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Service role can write business_overviews"
  ON public.business_overviews
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
